In [1]:
import os, sys
sys.path.append(os.getcwd())

import numpy as np
import tensorflow as tf
import scipy.misc
import imageio
from imageio import imwrite
from scipy.misc import imsave, imread

import keras
from keras.datasets import mnist, cifar10


(x_train, y_train), (x_test, y_test) = mnist.load_data()
(x_traincifar, y_traincifar), (x_testcifar, y_testcifar) = cifar10.load_data()
x_traincifar = x_traincifar.transpose(0,3,1,2)
print(x_traincifar.shape)

Using TensorFlow backend.


(50000, 3, 32, 32)


In [2]:
p_set = np.zeros(1)
print(p_set.shape)
p_new = np.append(p_set,0.1)
print(p_new.shape)

(1,)
(2,)


In [3]:
x1 = np.load('/Users/wildflowerlyi/Desktop/x_augmentation_array_1.npy')
y1 = np.load('/Users/wildflowerlyi/Desktop/y_augmentation_array_1.npy')
x2 = np.load('/Users/wildflowerlyi/Desktop/x_augmentation_array_2.npy')
y2 = np.load('/Users/wildflowerlyi/Desktop/y_augmentation_array_2.npy')
x3 = np.load('/Users/wildflowerlyi/Desktop/x_augmentation_array_3.npy')
y3 = np.load('/Users/wildflowerlyi/Desktop/y_augmentation_array_3.npy')
x4 = np.load('/Users/wildflowerlyi/Desktop/x_augmentation_array_4.npy')
y4 = np.load('/Users/wildflowerlyi/Desktop/y_augmentation_array_4.npy')
x5 = np.load('/Users/wildflowerlyi/Desktop/x_augmentation_array_5.npy')
y5 = np.load('/Users/wildflowerlyi/Desktop/y_augmentation_array_5.npy')
x6 = np.load('/Users/wildflowerlyi/Desktop/x_augmentation_array_6.npy')
y6 = np.load('/Users/wildflowerlyi/Desktop/y_augmentation_array_6.npy')
x7 = np.load('/Users/wildflowerlyi/Desktop/x_augmentation_array_7.npy')
y7 = np.load('/Users/wildflowerlyi/Desktop/y_augmentation_array_7.npy')
x8 = np.load('/Users/wildflowerlyi/Desktop/x_augmentation_array_8.npy')
y8 = np.load('/Users/wildflowerlyi/Desktop/y_augmentation_array_8.npy')
x9 = np.load('/Users/wildflowerlyi/Desktop/x_augmentation_array_9.npy')
y9 = np.load('/Users/wildflowerlyi/Desktop/y_augmentation_array_9.npy')
x10 = np.load('/Users/wildflowerlyi/Desktop/x_augmentation_array_10.npy')
y10 = np.load('/Users/wildflowerlyi/Desktop/y_augmentation_array_10.npy')
x11 = np.load('/Users/wildflowerlyi/Desktop/x_augmentation_array_11.npy')
y11 = np.load('/Users/wildflowerlyi/Desktop/y_augmentation_array_11.npy')
#TODO: change original image files to round

In [21]:
x_full = np.concatenate((x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11), axis=0)
y_full = np.concatenate((y1,y2,y3,y4,y5,y6,y7,y8,y9,y10,y11), axis=0)
print(x_full.shape)
print(y_full.shape)

(4500, 3, 32, 32)
(4500, 1, 10)


In [27]:
x_augmentation_set = np.around(x_full, 1)
x_augmentation_set[1,:]
y_augmentation_set = np.around(y_full, 1)
y_augmentation_set[1,:]
np.save('/Users/wildflowerlyi/Desktop/x_augmentation_array.npy', x_augmentation_set)
np.save('/Users/wildflowerlyi/Desktop/y_augmentation_array.npy', y_augmentation_set)

In [46]:
x_2250 = np.concatenate((x1,x2,x3,x4,x5,x6,x7), axis=0)
y_2250 = np.concatenate((y1,y2,y3,y4,y5,y6,y7), axis=0)
x_2250 = x_2250[0:2250,:]
y_2250 = y_2250[0:2250,:]
print(x_2250.shape)
print(y_2250.shape)
x_augmentation_set_2250 = np.around(x_2250, 1)
y_augmentation_set_2250 = np.around(y_2250, 1)
np.save('/Users/wildflowerlyi/Desktop/x_augmentation_array_2250.npy', x_augmentation_set_2250)
np.save('/Users/wildflowerlyi/Desktop/y_augmentation_array_2250.npy', y_augmentation_set_2250)

(2250, 3, 32, 32)
(2250, 1, 10)


In [4]:
x_1125 = np.concatenate((x1,x2,x3,x4), axis=0)
y_1125 = np.concatenate((y1,y2,y3,y4), axis=0)
x_1125 = x_1125[0:1125,:]
y_1125 = y_1125[0:1125,:]
print(x_1125.shape)
print(y_1125.shape)
x_augmentation_set_1125 = np.around(x_1125, 1)
y_augmentation_set_1125 = np.around(y_1125, 1)
np.save('/Users/wildflowerlyi/Desktop/x_augmentation_array_1125.npy', x_augmentation_set_1125)
np.save('/Users/wildflowerlyi/Desktop/y_augmentation_array_1125.npy', y_augmentation_set_1125)

(1125, 3, 32, 32)
(1125, 1, 10)


In [5]:
x_560 = np.concatenate((x1,x2), axis=0)
y_560 = np.concatenate((y1,y2), axis=0)
x_560 = x_560[0:560,:]
y_560 = y_560[0:560,:]
print(x_560.shape)
print(y_560.shape)
x_augmentation_set_560 = np.around(x_560, 1)
y_augmentation_set_560 = np.around(y_560, 1)
np.save('/Users/wildflowerlyi/Desktop/x_augmentation_array_560.npy', x_augmentation_set_560)
np.save('/Users/wildflowerlyi/Desktop/y_augmentation_array_560.npy', y_augmentation_set_560)

(560, 3, 32, 32)
(560, 1, 10)


In [32]:
print(x_augmentation_set.shape)
print(y_augmentation_set.shape)
print(y_augmentation_set[322,:])
np.around(y_augmentation_set[322,:],1)

(4500, 3, 32, 32)
(4500, 1, 10)
[[0.  0.  0.  0.  0.  0.6 0.4 0.  0.  0. ]]


array([[0. , 0. , 0. , 0. , 0. , 0.6, 0.4, 0. , 0. , 0. ]])

In [33]:
print(y_testcifar.shape)
print(x_testcifar.shape)
y_testcifar2 = keras.utils.to_categorical(y_testcifar, 10)
y_traincifar2 = keras.utils.to_categorical(y_traincifar, 10)
print(y_testcifar2.shape)
print(y_traincifar2.shape)

(10000, 1)
(10000, 32, 32, 3)
(10000, 10)
(50000, 10)


In [25]:
y_augmentation_set2 = y_augmentation_set.reshape(-1,10)
y_augmentation_set2.shape

(18, 10)

In [32]:
x_total = np.concatenate((x_traincifar, x_augmentation_set), axis=0)
y_total = np.concatenate((y_traincifar2, y_augmentation_set2), axis=0)
print(y_total.shape)
print(y_total[50017,:])

(50018, 10)
[0.1        0.         0.         0.         0.         0.
 0.         0.89999998 0.         0.        ]


In [ ]:
#x_total.shape
xrange(2)

In [ ]:
# READING IN AUGMENTATIONS TO TRAIN NEURAL NETWORKS: FINAL
# (1) Read in x and y augmentations as new_x and new_y
# (2) Transpose new_x = new_x.transpose(0, 2, 3, 1)
#     x_augmented = np.append(x_train, new_x, axis=0)
#     y_augmented = np.append(y_train, new_y, axis=0)

# Add the below text at the beginning of train_cifar10 files in each directory. Make sure the augmented files are 
# in each of the folders resnet_cifar, resnet_wide, resnet_densenet

In [ ]:
horse = imread('/Users/wildflowerlyi/Desktop/original_4.png')

In [ ]:
horse.shape

In [ ]:
np.save('/Users/wildflowerlyi/Desktop/horsearray.npy', horse)

In [ ]:
horsetest = np.load('/Users/wildflowerlyi/Desktop/horsearray.npy')

In [ ]:
horsetest.shape

In [11]:
import sklearn
from sklearn.model_selection import train_test_split
seed = 333
x_train45, x_val, y_train45, y_val = train_test_split(x_traincifar, y_traincifar, test_size=0.1, random_state=seed)  # random_state = seed

In [15]:
print(x_train45[1,:].shape)
print(x_train45[1,:].reshape(1, 3, 32, 32).shape)

(3, 32, 32)
(1, 3, 32, 32)


In [4]:
y_train45.shape

(45000, 1)

In [15]:
idx = np.where(np.equal(3,y_train45))
y_subset = y_train45[idx,:]
y_subset.shape

(2, 4477, 1)

In [16]:
print(idx)
print(idx[0].shape)
print(idx[1].shape)

(array([    8,     9,    18, ..., 44974, 44987, 44998]), array([0, 0, 0, ..., 0, 0, 0]))
(4477,)
(4477,)


In [17]:
print(idx[1][6:15])

[0 0 0 0 0 0 0 0 0]


In [103]:
idx1 = np.asarray(np.where(np.equal(0, y_train45))[0])
x_trainsubset1 = x_train45[idx1,:]
y_trainsubset1 = y_train45[idx1,:]
x_trainsubset1 = x_trainsubset1.reshape(-1, 3, 32, 32) 
y_trainsubset1 = y_trainsubset1.reshape(-1, 1)

In [7]:
range(9)

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [104]:
print(x_trainsubset1.shape)
print(y_trainsubset1.shape)
print(x_trainsubset1.shape[0])
print(x_train45.shape)

(4477, 3, 32, 32)
(4477, 1)
4477
(45000, 3, 32, 32)


In [94]:
import random
index = random.sample(range(x_trainsubset1.shape[0]),1)
print(index)
print(x_trainsubset1[index,:].shape)
print(y_trainsubset1[index,])

[1847]
(1, 3, 32, 32)
[[6]]


In [95]:
def color_grid_vis(X, nh, nw, save_path):
    # from github.com/Newmu
    X = X.transpose(0,2,3,1)
    h, w = X[0].shape[:2]
    img = np.zeros((h*nh, w*nw, 3))
    for n, x in enumerate(X):
        j = n/nw
        i = n%nw
        img[j*h:j*h+h, i*w:i*w+w, :] = x
    imwrite(save_path, img)

In [96]:
color_grid_vis(x_trainsubset1[index,:],1,1,'/Users/wildflowerlyi/Desktop/test.png')

In [107]:
print(y_trainsubset1[4200:4300])

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
