In [1]:
import os, sys
sys.path.append(os.getcwd())

import numpy as np
import tensorflow as tf
import scipy.misc
import imageio
from imageio import imwrite
from scipy.misc import imsave, imread

In [2]:
import tflib as lib
import tflib.sampling_loop
import tflib.ops.kl_unit_gaussian
import tflib.ops.kl_gaussian_gaussian
import tflib.ops.conv2d
import tflib.ops.linear
import tflib.ops.batchnorm
import tflib.ops.embedding

import os
import urllib
import gzip
import cPickle as pickle

import time
import functools
import random

DATASET = 'mnist_256' # mnist_256

In [3]:
p = 0.5
array1 = [1, 2, 3, 4]
array2 = [4, 5, 6, 7]
np.multiply(p, array1)

array([0.5, 1. , 1.5, 2. ])

In [4]:
classindices = [1,1]
hi = np.multiply(0.5, classindices) + np.multiply(0.5, classindices)
imsave('/Users/wildflowerlyi/Desktop/' + 'samples_{}.txt', hi)

/anaconda2/envs/tensorflow/lib/python2.7/site-packages/ipykernel_launcher.py:3: DeprecationWarning: `imsave` is deprecated!
`imsave` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imwrite`` instead.
  This is separate from the ipykernel package so we can avoid doing imports until


ValueError: 'arr' does not have a suitable array shape for any mode.

In [ ]:
classindices = np.array([[0,6],[3,8]])
classindices[0,]
classindices.shape[0]
idx = np.zeros(classindices.shape[0])
for classnums in xrange(classindices.shape[0]):
    idx[classnums] = 1

In [5]:
all_latents = np.zeros((3,8)).astype('float32')
print(all_latents)
all_latents = np.delete(all_latents, -1, axis=1)
print(all_latents)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [11]:
import itertools
pairlist = np.array([1,2,3,4,5])
listcombos = list(itertools.combinations(pairlist,2))
#print(listcombos)
arraycombos = np.array(list(itertools.combinations(pairlist,2)))
print(arraycombos)
print(arraycombos.shape[0])

meanvec = np.mean([arraycombos[1],arraycombos[2]], axis=0)
meow = np.zeros(1)
print(meanvec)

[[1 2]
 [1 3]
 [1 4]
 [1 5]
 [2 3]
 [2 4]
 [2 5]
 [3 4]
 [3 5]
 [4 5]]
10
[1 3]
[1 4]
4
[1 3]
[1.  3.5]


In [19]:
# Test how to index things
y_train = [4, 0, 1, 2, 3, 4]
idx = np.where(np.equal(y_train[0],y_train))
print(idx[0])
idx1 = np.where(np.equal(y_train,y_train[0]))
print(idx1[0][0])

[0 5]
0


In [ ]:
# How data is loaded into PixelVAE
data = urllib.urlretrieve('http://www.iro.umontreal.ca/~lisa/deep/data/mnist/mnist.pkl.gz', 'mnist_test.gz')[0]

with gzip.open(data, 'rb') as f:
    train_data, dev_data, test_data = pickle.load(f)

In [ ]:
#print(train_data[0][1]) # pixels are in the range 0-1
train_data[0].shape

In [ ]:
def mnist_reshape(data):
    
    images, targets = data
    images = images.astype('float32')
    images = images.reshape(-1, 784)
    images2 = (images*(256-1e-8)).astype('int32')
    
    targets = targets.astype('float32')

    return(np.copy(images2), np.copy(targets))

In [ ]:
train_data = mnist_reshape(train_data)

In [ ]:
index = np.random.randint(0, len(train_data[1]), 2)

In [ ]:
print(train_data[0][index[0]]) # pixels are now integers

In [ ]:
image_samples = train_data[0][index]

In [ ]:
label_samples = train_data[1][index]

In [ ]:
new_target = (np.mean(label_samples))

In [ ]:
# save images as uint8 arrays
image_samples_int8  = image_samples.astype(np.uint8)

In [ ]:
samples_new = image_samples, label_samples

In [ ]:
sample1 = image_samples[1], label_samples[1]

In [ ]:
#print(samples_new)

In [ ]:
#print(samples_new[0][0]) # before converting to uint8

In [ ]:
#print(image_samples_int8[0]) # after converting to uint8

In [ ]:
# Read in png file and target as arrays
testimage = imread('/Users/wildflowerlyi/Desktop/Github/reconstructions_mnist/original_0.png')
reconimage = imread('/Users/wildflowerlyi/Desktop/Github/reconstructions_mnist/reconstruction_0.png')
print(testimage.shape)
print(testimage.dtype.name)
print(reconimage.dtype.name)
imwrite('/Users/wildflowerlyi/Desktop/test.png',testimage)
testimage2 = np.load('/Users/wildflowerlyi/Desktop/Github/reconstructions_mnist/x_augmentation_array.npy')
print(testimage2.shape)
print(testimage2.dtype.name)
print(testimage2)

In [ ]:
hi = np.zeros([1,1,28,28], dtype='uint8')
print(hi.dtype.name)
hi2 = testimage2.astype(np.uint8)
print(hi2.dtype.name)

In [ ]:
e = np.array([1, 0.4, 0.9])
e2 = e.astype(np.uint8)
print(e2)
import keras
e3 = keras.utils.to_categorical(e, num_classes=3)
print(e3)
print(e3 + 0.1)

In [ ]:
def color_grid_vis(X, nh, nw, save_path):
    # from github.com/Newmu
    X = X.transpose(0,2,3,1)
    h, w = X[0].shape[:2]
    img = np.zeros((h*nh, w*nw, 3))
    for n, x in enumerate(X):
        j = n/nw
        i = n%nw
        img[j*h:j*h+h, i*w:i*w+w, :] = x
    imwrite(save_path, img)

In [5]:
# Import Keras
import keras
from keras.datasets import mnist, cifar10
import imageio
from tempfile import TemporaryFile

#(x_train, y_train), (x_test, y_test) = mnist.load_data()
(x_traincifar, y_traincifar), (x_testcifar, y_testcifar) = cifar10.load_data()

In [8]:
print(x_traincifar.shape)
x_traincifar_new = x_traincifar.transpose(0,3,1,2)
print(x_traincifar_new.shape)
x_traincifar_new = x_traincifar.transpose(0,3,1,2)

(50000, 32, 32, 3)
(50000, 3, 32, 32)


In [ ]:
new_xtrain = x_train.reshape(-1, 1, 28, 28)
new_xtrain.shape
new_ytrain = y_train.reshape(-1, 1)
new_ytrain.shape
new_xtrain.shape
new_xtrain[0,]

In [ ]:
# Test how to index things
idx = np.where(np.equal(4,new_ytrain))
print(idx[0])
new_ytrain = np.array(new_ytrain)
new_xtrain = np.array(new_xtrain)
new_xtrain[idx[0]].shape
x2 = new_xtrain[idx[0]][1].reshape(-1, 1, 28, 28)
x2.shape
new_xtrain.shape

In [ ]:
# Save a generated image and its corresponding target as a tuple
outfile = TemporaryFile()
#np.savez(outfile,image = testimage, label = testtarget)
np.save(outfile, image = testimage)
np.save()

In [ ]:
outfile.seek(0)
npzfile = np.load(outfile)

In [ ]:
npzfile.files

In [ ]:
# Reshape the image
# If MNIST
newimage = sample1[0].reshape(-1, 28, 28)
# If CIFAR
#newimage = sample1[0].reshape(-1, 3, 32, 32)

In [ ]:
# Add image and target to dataset
x_train_aug = np.append(x_train, newimage2, axis=0)
y_train_aug = np.append(y_train, sample1[1])

In [ ]:
np.save('/Users/wildflowerlyi/Desktop/test', x_train_aug)

In [ ]:
x_augmentations_arrays = np.load('/Users/wildflowerlyi/Desktop/test.npy')

In [ ]:
# SAVING AUGMENTATIONS: FINAL
# (0) Initialize image array
# (1) Produce image array
# (2) Add image array to those before
# (3) Save final array at end of for loop

In [ ]:
# Insert this at line 798
x_augmentations_array = []

# Insert this line under the sample generation loop in line 823
print "Appending image array to those previously generated"
    x_augmentations_array = np.append(x_augmentations_array, samples, axis=0)

# Insert this line after all images have been added, after line 834 (make sure not indented)
np.save('x_augmentations_array', x_augmentations_array)

In [ ]:
# READING IN AUGMENTATIONS TO TRAIN NEURAL NETWORKS: FINAL
# (1) Read in x and y augmentations as new_x and new_y
# (2) Transpose new_x = new_x.transpose(0, 3, 1, 2)
#     x_augmented = np.append(x_train, new_x, axis=0)
#     y_augmented = np.append(y_train, new_y, axis=0)

# Add the below text at the beginning of train_cifar10 files in each directory. Make sure the augmented files are 
# in each of the folders resnet_cifar, resnet_wide, resnet_densenet

In [ ]:
# Import Keras
import keras
from keras.datasets import mnist, cifar10
import numpy as np

(x_train, y_train), (x_test, y_test) = mnist.load_data()
(x_traincifar, y_traincifar), (x_testcifar, y_testcifar) = cifar10.load_data()

# Load augmented arrays
new_x = np.load('/Users/wildflowerlyi/Desktop/Github/NN_calibration/scripts/resnet_cifar/x_augmentation_array.npy')
new_y = np.load('/Users/wildflowerlyi/Desktop/Github/NN_calibration/scripts/resnet_cifar/y_augmentation_array.npy')

# Reshape from (H,W,CH) to (CH,H,W)
# new_x = np.transpose(new_x, (2, 1, 0)) # Only for CIFAR

# Add images and targets to original dataset
x_train_aug = np.append(x_train, new_x, axis=0)
y_train_aug = np.append(y_train, new_y, axis=0)